language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script:
  - echo "OS: $TRAVIS_OS_NAME"
  - ./configure --with-embedded-sqlite3
  - make
  - ./tests
  - make clean
  - ./configure --with-embedded-sqlite3 --disable-network
  - make
  - ./tests

notifications:
  email: true

before_install:
  - [ "$TRAVIS_OS_NAME" == "linux" ] && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - [ "$TRAVIS_OS_NAME" == "linux" ] && sudo apt-get update -qq

install:
  - [ "$TRAVIS_OS_NAME" == "linux" ] && sudo apt-get install -qq g++-4.8
  - [ "$TRAVIS_OS_NAME" == "linux" ] && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - [ "$TRAVIS_OS_NAME" == "linux" ] && sudo apt-get install -qq libasound2-dev libpulse-dev libaudio-dev libx11-dev  libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev  libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev  libudev-dev libgles1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev
