language:
  - cpp

compiler:
  - gcc
  - clang

os:
  - linux

script:
  - git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=caveexpress && make -j 2 && ./tests
  - git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=caveexpress --disable-network && make -j 2 && ./tests
  - git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=cavepacker && make -j 2 && ./tests
  - git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=cavepacker --disable-network && make -j 2 && ./tests
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=caveexpress --target-os=android && make -j 2 && ./tests; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=caveexpress --target-os=nacl && make -j 2 && ./tests; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=cavepacker --target-os=android && make -j 2 && ./tests; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git checkout -f; make clean && ./configure --with-embedded-sqlite3 --app=cavepacker --target-os=nacl && make -j 2 && ./tests; fi

notifications:
  email: true

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make nacl-setup; make android-setup; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq libasound2-dev libpulse-dev libaudio-dev libx11-dev  libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev  libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev  libudev-dev libgles1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev; fi
