os:
  - linux
  - osx

sudo: false

language:
  - cpp

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "G4/gfaLtLwXbfTNcGwQ2UsGs5b/EAIeRKkfNKoznWhBxs69AesV0SWhqb/Tr+/EcKEVV+Anh1Akj6YQYFIl6/4jNP7SrVPShTAB3Fo0lXlDwzzt+xK2em+2WA05kOMRBKPmoriOFUcAy1QZ8iOX2V5NZhSrF5MpnBsoU/vbHpeg="
  matrix:
    - USE_BUILTIN=ON
    - USE_BUILTIN=OFF

addons:
  coverity_scan:
    project:
      name: "mgerhardy/caveexpress"
      description: "Build submitted via Travis CI"
    notification_email: martin.gerhardy@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make -j 4"
    branch_pattern: coverity_scan
  apt:
    packages:
    - libbox2d-dev
    - libglm-dev
    - libgtest-dev
    - libsqlite3-dev
    - liblua5.2-dev
    - zlib1g-dev
    - g++-5
    - gcc-5
    - clang
    - libc6:i386
    - lua5.1
    - libdbus-1-dev
    - build-essential
    - mercurial
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - libasound2-dev
    - libpulse-dev
    - libaudio-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxxf86vm-dev
    - libxss-dev
    - libgl1-mesa-dev
    - libesd0-dev
    - libdbus-1-dev
    - libudev-dev
    - libgles1-mesa-dev
    - libgles2-mesa-dev
    - libegl1-mesa-dev
    - libibus-1.0-dev
    sources:
    - ubuntu-toolchain-r-test
    - zoogie-sdl2-snapshots

# currently disabled, because sdl2 ppa is not yet available
#    - libsdl2-dev
#    - libsdl2-net-dev
#    - libsdl2-image-dev
#    - libsdl2-mixer-dev
# weird, but there is no libyajl2-dev package
#    - libyajl2-dev

script:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pkg-config --version; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then g++-5 --version; fi
  - clang++ --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir build-$TRAVIS_OS_NAME && cd build-$TRAVIS_OS_NAME && cmake .. -DUSE_BUILTIN=$USE_BUILTIN && make -j 4 && cd .. && ./tests && ./tests-caveexpress; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir build-$TRAVIS_OS_NAME && cd build-$TRAVIS_OS_NAME && cmake -G Xcode .. -DUSE_BUILTIN=$USE_BUILTIN && ls && xcodebuild -list -project Project.xcodeproj && xcodebuild -project Project.xcodeproj -target ALL_BUILD | xcpretty -f `xcpretty-travis-formatter` && cd .. && ./Debug/tests && ./Debug/tests-caveexpress; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir build-ios && cd build-ios && cmake -G Xcode .. -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/ios-toolchain.cmake -DUSE_BUILTIN=$USE_BUILTIN && ls && xcodebuild -list -project Project.xcodeproj && xcodebuild -project Project.xcodeproj -target ALL_BUILD | xcpretty -f `xcpretty-travis-formatter`; fi

notifications:
  email:
    - martin.gerhardy@gmail.com

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

cache: apt
