language:
  - cpp

branches:
 only:
   - master

compiler:
  - gcc
  - clang

os:
  - linux

script:
  - mkdir build-bundled; cd build-bundled; cmake ..; make; cd ..; ./build-bundled/tests
  - sudo apt-get install -qq libbox2d-dev libyajl-dev libglm-dev libgtest-dev libsdl2-dev libsdl2-net-dev libsdl2-image-dev libsdl2-mixer-dev libsqlite3-dev liblua5.2-dev zlib1g-dev
  - mkdir build-systemwide; cd build-systemwide; cmake ..; make; cd ..; ./build-systemwide/tests

notifications:
  email: true

before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libc6:i386
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - sudo apt-get install -qq lua5.1 libdbus-1-dev
  - sudo apt-get install -qq -d libbox2d-dev libyajl-dev libglm-dev libgtest-dev libsdl2-dev libsdl2-net-dev libsdl2-image-dev libsdl2-mixer-dev libsqlite3-dev liblua5.2-dev zlib1g-dev

cache: apt
