version: 0.1-{build}

os:
  - Windows Server 2012 R2

environment:
  NSIS_ROOT: C:\nsis

configuration: Release

install:
  - cinst -y -installArgs /D=%NSIS_ROOT% nsis

branches:
  only:
  - master

clone_depth: 10

before_build:
  - cmake -DTOOLS=OFF -G "Visual Studio 12"

after_build:
  - '"%NSIS_ROOT%\makensis" -DPRODUCT_NAME=cavepacker -DPRODUCT_VERSION=%APPVEYOR_BUILD_VERSION% contrib/installer/windows/setup.nsi'
  - '"%NSIS_ROOT%\makensis" -DPRODUCT_NAME=caveexpress -DPRODUCT_VERSION=%APPVEYOR_BUILD_VERSION% contrib/installer/windows/setup.nsi'

build:
  parallel: true
  project: caveproductions.sln

artifacts:
  - name: Installer CaveExpress
    path: contrib/installer/windows/caveexpress-$(APPVEYOR_BUILD_VERSION).exe
  - name: Installer CavePacker
    path: contrib/installer/windows/cavepacker-$(APPVEYOR_BUILD_VERSION).exe

test_script:
  - cmd: tests.exe --gtest_filter=-Network* --gtest_output=xml:tests.xml
  - cmd: tests_caveexpress.exe --gtest_output=xml:tests_caveexpress.xml
  - cmd: tests_cavepacker.exe --gtest_output=xml:tests_cavepacker.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests_cavepacker.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests_caveexpress.xml))
