os:
  - Windows Server 2012 R2

environment:
  NSIS_ROOT: C:\nsis

configuration: Release

install:
  - cinst -y -installArgs /D=%NSIS_ROOT% nsis

branches:
  only:
  - master

clone_depth: 10

before_build:
  - cmake -DTOOLS=OFF -G "Visual Studio 12"

after_build:
  - '"%NSIS_ROOT%\makensis" -DPRODUCT_NAME=cavepacker -DPRODUCT_VERSION=0.1 contrib/installer/windows/setup.nsi'
  - '"%NSIS_ROOT%\makensis" -DPRODUCT_NAME=caveexpress -DPRODUCT_VERSION=0.1 contrib/installer/windows/setup.nsi'

build:
  parallel: true
  project: caveproductions.sln

artifacts:
  - name: Installer CaveExpress
    path: 'caveexpress-*.exe'
  - name: Installer CavePacker
    path: 'cavepacker-*.exe'
